#!/bin/bash
__usage="
Usage: $(basename $0) [PORT]
Note: you probably want to edit the command variable below. 

Options:
  PORT                         Port in which to run pluto. Passed by init.
"


command="
import Pluto;
Pluto.run(
    host=\"${3}\",
    port=8888,
    launch_browser=false,
    require_secret_for_open_links=false,
    require_secret_for_access=false,
)"
echo ${command}
julia --optimize=0 -e "${command}"
