name: pluto-notebook

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with: # make sure username & password/token matches your registry
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.TOKEN_GHCR }}
          DOCKER_REGISTRY: "ghcr.io"
          ADDITIONAL_TAG: "latest"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GHCR }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./fasterbinder
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pluto-on-binder-faster:latest
