name: pluto-notebook

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with: # make sure username & password/token matches your registry
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.TOKEN_GHCR }}
          DOCKER_REGISTRY: "ghcr.io"
          ADDITIONAL_TAG: "latest"
      - name: checkout dockerimage
        uses: actions/checkout@v2
        with:
          ref: binder-consumer
      - run:
          echo FROM ${{ IMAGE_SHA_NAME }} >> binder/Dockerfile
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerfile"
          git push
