name: pluto-notebook

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GHCR }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pluto-notebook-on-binder:latest
      - name: Create Updated Dockerfile
        run: |
          echo FROM ghcr.io/${{ github.repository_owner }}/pluto-notebook-on-binder@${{ steps.build.outputs.digest  }} > binder/Dockerfile
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerfile"
          git push
