name: Basic Dockerfile

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      # - uses: jupyterhub/repo2docker-action@master
      #   with: # make sure username & password/token matches your registry
      #     DOCKER_USERNAME: ${{ github.repository_owner }}
      #     DOCKER_PASSWORD: ${{ secrets.TOKEN_GHCR }}
      #     DOCKER_REGISTRY: "ghcr.io"
      #     ADDITIONAL_TAG: "latest"

      - name: checkout dockerimage
        uses: actions/checkout@v2
        with:
          ref: binder-consumer
      - name: Create Updated Dockerfile
        run: |
          echo FROM ghcr.io/${{ github.repository_owner }}/pluto-on-binder@sha256:${GITHUB_SHA} > binder/Dockerfile
          echo FROM ghcr.io/${{ github.repository_owner }}/pluto-on-binder@sha256:${GITHUB_SHA}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerfile"
          git push
